services:
  - type: web
    name: python-fastapi-quote
    runtime: docker
    dockerfilePath: ./quote/Dockerfile
    - key: PORT
      value: 8000
  - type: web
    name: python-fastapi-search
    runtime: docker
    dockerfilePath: ./search/Dockerfile
    - key: PORT
      value: 8002
  - type: web
    name: python-fastapi-fetcher
    runtime: docker
    dockerfilePath: ./fetcher/Dockerfile
    - key: PORT
      value: 8001
